services:
  portico_outlook:
    container_name: portico_outlook
    hostname: portico_outlook
    build:
        context: .
        dockerfile: Dockerfile
        args:
           http_proxy: ${http_proxy}
           https_proxy: ${https_proxy}
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on: []
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - portico_internal

networks:
  portico_internal:
    external: true  # Reference the existing external network
