services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
        args:
           http_proxy: ${http_proxy}
           https_proxy: ${https_proxy}
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on: []
    extra_hosts:
      - "host.docker.internal:host-gateway"

